# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: aws-tasks 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "aws-tasks".freeze
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Sam Reh".freeze]
  s.date = "2019-04-23"
  s.description = "AWS helper tasks for DB and such".freeze
  s.email = "samuelreh@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "aws-tasks.gemspec",
    "lib/aws-tasks.rb",
    "lib/tasks/aws.rake"
  ]
  s.homepage = "http://github.com/attribution/aws-tasks".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.14.3".freeze
  s.summary = "AWS helper tasks".freeze

  s.add_dependency 'aws-sdk-rds', '~> 1'
  s.add_dependency 'aws-sdk-redshift', '~> 1'
end

